/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fff8f6',
        'on-background': '#231915',
        surface: '#fff8f6',
        'surface-dim': '#e9d6ce',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1eb',
        'surface-container': '#feeae1',
        'surface-container-high': '#f8e4dc',
        'surface-container-highest': '#f2dfd6',
        'surface-variant': '#f2dfd6',
        'on-surface': '#231915',
        'on-surface-variant': '#564339',
        'inverse-surface': '#392e29',
        'inverse-on-surface': '#ffede6',
        outline: '#897267',
        'outline-variant': '#ddc1b4',
        primary: '#783100',
        'on-primary': '#ffffff',
        'primary-container': '#9d4300',
        'on-primary-container': '#ffceb6',
        'inverse-primary': '#ffb690',
        'primary-fixed': '#ffdbca',
        'primary-fixed-dim': '#ffb690',
        'on-primary-fixed': '#341100',
        'on-primary-fixed-variant': '#783200',
        secondary: '#785a00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc425',
        'on-secondary-container': '#6d5200',
        'secondary-fixed': '#ffdf9a',
        'secondary-fixed-dim': '#f7be1d',
        'on-secondary-fixed': '#251a00',
        'on-secondary-fixed-variant': '#5a4300',
        tertiary: '#004688',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005eb2',
        'on-tertiary-container': '#c5d9ff',
        'tertiary-fixed': '#d5e3ff',
        'tertiary-fixed-dim': '#a7c8ff',
        'on-tertiary-fixed': '#001b3c',
        'on-tertiary-fixed-variant': '#004788',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'cream-bg': '#fdfcf0',
        terracotta: '#9d4300',
        mustard: '#eab308',
        'leaf-success': '#006e2f',
        'slate-neutral': '#334155',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '32px',
        'section-gap': '96px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['44px', { lineHeight: '52px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}